annisaStory5/urls.py
from django.contrib import admin
from django.urls import include, path

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include(('main.urls'), 'main'), name="main"),
    path('', include(('story4.urls'), 'story4'), name="story4"),
    path('', include(('story5.urls'), 'story5'), name="story5"),
    path('', include(('story7.urls'), 'story7'), name="story7"),
    path('', include(('story8.urls'), 'story8'), name="story8"),
    path('', include(('story9.urls'), 'story9'), name="story9"),
]

main/urls.py
from django.urls import path

from . import views

app_name = 'main'

urlpatterns = [
    path('', views.profile, name='profile'),
]

story5/urls.py
from django.urls import path

from . import views

app_name = 'story5'

urlpatterns = [
    path('simpanmatkul', views.simpanmatkul, name='simpanmatkul'),
    path('bacamatkul', views.bacamatkul, name='bacamatkul'),
    path('detailmatkul/<str:id_det>', views.detailmatkul, name='detailmatkul'),
    path('cekhapusmatkul', views.hapusmatkul, name='hapusmatkul'),
    path('hapusmatkul/<str:id_det>', views.hapusmatkul, name='hapusmatkul'),
]

story5/models.py
from django.db import models

# Create your models here.
class MataKuliah(models.Model):
    namamatkul = models.CharField(max_length=30)
    dosen = models.CharField(max_length=30)
    sks = models.CharField(max_length=10)
    deskripsi = models.CharField(max_length=70)
    semester = models.CharField(max_length=20)
    ruang = models.CharField(max_length=10)

story5/forms.py
from django import forms
from .models import MataKuliah

class Input_Form(forms.ModelForm):
        class Meta:
            model = MataKuliah
            fields = ['namamatkul', 'dosen', 'sks', 'deskripsi','semester', 'ruang']

        error_messages={
            'required' : 'Please Type'
        }

        matkul_attrs = {
            'type' : 'text',
            'class' : 'form-control',
            'placeholder' : 'PPW'
        }

        dosen_attrs = {
            'type' : 'text',
            'class' : 'form-control',
            'placeholder' : 'Bu Iis'
        }

        sks_attrs = {
            'type' : 'text',
            'class' : 'form-control',
            'placeholder' : '3 sks'
        }

        deskripsi_attrs = {
            'type' : 'text',
            'class' : 'form-control',
            'placeholder' : 'PPW mempelajari website'
        }

        semester_attrs = {
            'type' : 'text',
            'class' : 'form-control',
            'placeholder' : 'Gasal 2020/2021'
        }

        ruang_attrs = {
            'type' : 'text',
            'class' : 'form-control',
            'placeholder' : 'R.2016'
        }


        namamatkul = forms.CharField(label='Nama Mata Kuliah', required=True, max_length=30, widget=forms.TextInput(attrs=matkul_attrs))
        dosen = forms.CharField(label='Dosen Pengajar', required=True, max_length=30, widget=forms.TextInput(attrs=dosen_attrs))
        sks = forms.CharField(label='Jumlah SKS', required=True, max_length=10, widget=forms.TextInput(attrs=sks_attrs))
        deskripsi = forms.CharField(label='Deskripsi', required=True, max_length=70, widget=forms.TextInput(attrs=deskripsi_attrs))
        semester = forms.CharField(label='Semester Tahun', required=True, max_length=20, widget=forms.TextInput(attrs=semester_attrs))
        ruang = forms.CharField(label='Ruang Kelas', required=True, max_length=10, widget=forms.TextInput(attrs=ruang_attrs))

story5/views.py
from django.shortcuts import render, redirect
from django.http import HttpResponseRedirect
from .forms import Input_Form
from .models import MataKuliah

# Create your views here.
response = {}
def simpanmatkul(request):
    form = Input_Form(request.POST or None)
    if request.method=="POST":
        if form.is_valid:
            form.save()
            return HttpResponseRedirect('bacamatkul')
    else:
        form = Input_Form()
        response['form'] = form

        matkul=MataKuliah.objects.all()
        response['matkul'] = matkul

        return render(request, 'story5/matkul.html', response)

def bacamatkul(request):
    return HttpResponseRedirect('simpanmatkul')

def detailmatkul(request, id_det):
    details = MataKuliah.objects.get(id=id_det)
    response['matkultujuan'] = details
    return render (request, 'story5/detailmatkul.html', response)

def hapusmatkul(request, id_det):
    details = MataKuliah.objects.get(id=id_det)
    details.delete()
    return HttpResponseRedirect('/simpanmatkul')

story5/templates/story5/detailmatkul.html
{% extends 'base.html' %}
{% load static %}

<!DOCTYPE html>
<html lang="en">

<head>
    
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    {% block style %}
    <link rel="stylesheet" href="{% static 'story5/css/matkul.css' %}">
    
    <link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.5.2/css/bootstrap.min.css" integrity="sha384-JcKb8q3iqJ61gNV9KGb8thSsNjpSL0n8PARn9HuZOnIxN0hoP+VmmDGMN5t9UJ0Z" crossorigin="anonymous">
    {% endblock style %}
    <title> Website Kak PW </title>
</head>

{% block content %}
<body>
    <section id="tabeldetail">
        <h4> Detail Mata Kuliah: </h4>
        <table class="table table-hover table-dark">
            <thead>
            <tr>
                <th scope="col">Keterangan</th>
                <th scope="col">Komponen</th>
            </tr>
            </thead>
            <tbody>
            <tr>
                <td> Nama Mata Kuliah </td>
                <td> {{matkultujuan.namamatkul}} </td>
            </tr>
            <tr>
                <td> Dosen Pengajar </td>
                <td> {{matkultujuan.dosen}} </td>
            </tr>
            <tr>
                <td> Jumlah SKS </td>
                <td> {{matkultujuan.sks}} </td>
            </tr>
            <tr>
                <td> Deskripsi </td>
                <td> {{matkultujuan.deskripsi}} </td>
            </tr>
            <tr>
                <td> Semester Tahun</td>
                <td> {{matkultujuan.semester}} </td>
            </tr>
            <tr>
                <td> Ruang Kelas</td>
                <td> {{matkultujuan.ruang}} </td>
            </tr>
            </tbody>
        </table>
        <a href="{% url 'story5:simpanmatkul' %}">
            <button class="btn btn-primary">Kembali</button>
        </a>
    </section>
    <img id="asetoval3" src="{% static 'story5/img/AsetOval3.png' %}" alt="asset">
</body>
{% endblock content %}

</html>

story5/templates/story5/matkul.html
{% extends 'base.html' %}
{% load static %}

<!DOCTYPE html>
<html lang="en">

<head>
    
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    {% block style %}
    <link rel="stylesheet" href="{% static 'story5/css/matkul.css' %}">
    
    <link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.5.2/css/bootstrap.min.css" integrity="sha384-JcKb8q3iqJ61gNV9KGb8thSsNjpSL0n8PARn9HuZOnIxN0hoP+VmmDGMN5t9UJ0Z" crossorigin="anonymous">
    {% endblock style %}
    <title> Website Kak PW </title>
</head>

{%block content%}
<body>
    <section id="matakuliah">
        <div class="matakuliah col">
            <h4> MATA KULIAH YANG SAYA AMBIL </h4>
            <div class="middle row">
                <form action="simpanmatkul" method="POST">
                    {% csrf_token %}
                    <div class="form-group">
                        {{form.as_p}}
                    </div>
                    <button type="submit" class="btn btn-primary">Submit</button>
                </form>
                <table class="table table-hover table-dark">
                    <thead>
                      <tr>
                        <th scope="col">Nama Mata Kuliah</th>
                        <th scope="col">Detail</th>
                      </tr>
                    </thead>
                    <tbody>
                    {% if matkul %}
                        {% for i in matkul %}
                      <tr>
                        <td> {{i.namamatkul}} </td>
                        <td> 
                            <a href="{% url 'story5:detailmatkul' i.id %}"> 
                                <button class="btn btn-primary intabel">Detail</button>
                            </a> </td>
                        <td> 
                            <a href="{% url 'story5:hapusmatkul' i.id%}"> 
                                <button class="btn btn-primary intabel" method="POST">Hapus</button>
                            </a> 
                        </td>
                      </tr>
                      {%endfor%}
                        {%endif%}
                    </tbody>
                  </table>
            </div>
        </div>
        
    </section>
    
    
</body>
{%endblock content%}
</html>