annisaStory5/urls.py
from django.contrib import admin
from django.urls import include, path

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include(('main.urls'), 'main'), name="main"),
    path('', include(('story4.urls'), 'story4'), name="story4"),
    path('', include(('story5.urls'), 'story5'), name="story5"),
    path('', include(('story7.urls'), 'story7'), name="story7"),
    path('', include(('story8.urls'), 'story8'), name="story8"),
    path('', include(('story9.urls'), 'story9'), name="story9"),
]

main/urls.py
from django.urls import path

from . import views

app_name = 'main'

urlpatterns = [
    path('', views.profile, name='profile'),
]

story4/urls.py
from django.urls import path

from . import views

app_name = 'story4'

urlpatterns = [
    path('profile2', views.profile2, name='profile2'),
    path('hobby', views.hobby, name='hobby'),
]

story5/urls.py
from django.urls import path

from . import views

app_name = 'story5'

urlpatterns = [
    path('simpanmatkul', views.simpanmatkul, name='simpanmatkul'),
    path('bacamatkul', views.bacamatkul, name='bacamatkul'),
    path('detailmatkul/<str:id_det>', views.detailmatkul, name='detailmatkul'),
    path('cekhapusmatkul', views.hapusmatkul, name='hapusmatkul'),
    path('hapusmatkul/<str:id_det>', views.hapusmatkul, name='hapusmatkul'),
]

story7/urls.py
from django.urls import path

from . import views

app_name = 'story7'

urlpatterns = [
    path('kegiatan/', views.kegiatan, name='kegiatan'),
]

story8/urls.py
from django.urls import path

from . import views

app_name = 'story8'

urlpatterns = [
    path('ajax/', views.ajax, name='ajax'),
    path('data/', views.data, name='data'),
]

templates/base.html
{% load static %}
<!DOCTYPE html>
<html lang="en">

<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <!-- CSS -->
    <link rel="stylesheet" href="{% static 'css/style.css' %}">
    
    <!-- BOOTSTRAP -->
    <link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.5.2/css/bootstrap.min.css" integrity="sha384-JcKb8q3iqJ61gNV9KGb8thSsNjpSL0n8PARn9HuZOnIxN0hoP+VmmDGMN5t9UJ0Z" crossorigin="anonymous">
    
    <!-- CSS -->
    <link rel="stylesheet" href="https://cdn.jsdelivr.net/npm/bootstrap@4.5.3/dist/css/bootstrap.min.css" integrity="sha384-TX8t27EcRE3e/ihU7zmQxVncDAy5uIKz4rEkgIXeMed4M0jlfIDPvg6uqKI2xXr2" crossorigin="anonymous">

    <!-- jQuery and JS bundle w/ Popper.js -->
    <script src="https://code.jquery.com/jquery-3.5.1.slim.min.js" integrity="sha384-DfXdz2htPH0lsSSs5nCTpuj/zy4C+OGpamoFVy38MVBnE+IbbVYUew+OrCXaRkfj" crossorigin="anonymous"></script>
    <script src="https://cdn.jsdelivr.net/npm/bootstrap@4.5.3/dist/js/bootstrap.bundle.min.js" integrity="sha384-ho+j7jyWK8fNQe+A12Hb8AhRq26LrZ/JpcUGGOn+Y7RsweNrtN/tE3MoK7ZeZDyx" crossorigin="anonymous"></script>

    
    <!-- CSS EXTENDS -->
    {% block style %}
    {% endblock style %}

    <!-- {% block meta %}
    {% endblock meta %} -->
</head>

<body>
    <nav class="navbar navbar-expand-lg navbar-dark">
        <a class="navbar-brand">
            <img id="logo" src="{% static 'main/img/Logo.png' %}">
        </a>
        <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarNavAltMarkup" aria-controls="navbarNavAltMarkup" aria-expanded="false" aria-label="Toggle navigation">
            <span class="navbar-toggler-icon"></span>
        </button>
        <div class="collapse navbar-collapse" id="navbarNavAltMarkup">
            <div class="navbar-nav">
              <a class="nav-item nav-link" href="{% url 'main:profile' %}">Profile</a>
              <a class="nav-item nav-link" href="{% url 'story4:profile2' %}">Profile2</a>
              <a class="nav-item nav-link" href="{% url 'story4:hobby' %}">Hobby</a>
              <a class="nav-item nav-link" href="{% url 'story5:simpanmatkul'%}">Mata Kuliah</a>
              <a class="nav-item nav-link" href="{% url 'story7:kegiatan'%}">Kegiatan</a>
              <a class="nav-item nav-link" href="{% url 'story8:ajax'%}">Search</a>
            </div>
            <div class="nav navbar-nav navbar-right">
                {%if user.is_authenticated%}
                <a class="nav-item nav-link" href="{% url 'story9:logoutAkun'%}">Logout</a>
                <a class="nav-item nav-link">Hallo {{user.first_name}} {{user.last_name}} :) </a>
                {%else%}
                <a class="nav-item nav-link" href="{% url 'story9:loginAkun'%}">Login</a>
                <a class="nav-item nav-link" href="{% url 'story9:register'%}">Register</a>
                {%endif%}
            </div>
        </div>
    </nav>
    {% block content %}
    {% endblock content %}
    <footer id="contactperson">
        <div class="footer col">
                <h7>Contact Person :</h7>
                <div class="sosmed row">
                    <a href="https://www.instagram.com/ichadevii/"> 
                        <img id="instagram" src="{% static 'main/img/Instagram.png' %}" alt="Instagram Saya">
                    </a> 
                    <a href="https://www.line.me/ichadevii/">
                        <img  id="line" src="{% static 'main/img/Line.png' %}" alt="Line Saya">
                    </a>
                    <a href="http://twitter.com/annisadevin/"> 
                        <img  id="twitter" src="{% static 'main/img/Twitter.png'%}" alt="Twitter Saya">
                    </a> 
                    <a href="adevi.nurmalasari@gmail.com">
                        <img  id="email" src="{% static 'main/img/Email.png' %}" alt="Email Saya">
                    </a>
                </div>
        </div>
    </footer>
    <script src="{% static 'story8/javascript/ajax.js' %}" type="text/javascript"></script>
</body>
  
</html>